### ISSUE TITLE
multiple pivot columns and open/collapse

### ISSUE THREAD

**Issue by simovesterinen** [janusschmidt/jquery.pivot#17]
Hi,

Hi have testing your awesome pivot tool. 

Is it so that there is no possibility to add multiple pivot columns?
For example in Excel you're able to open/collapse members from multiple column members too.
 
To really use the power of pivot it would be very nice have this feature.

Here is a example json of the columns to help you understand what i mean:

columns: [

// columns of the pivot table:
			{ colvalue: 'Yearkey', coltext: 'Year_Name', header: 'Year Name', sortbycol: 'Yearkey', groupbyrank: 1, pivot: true, result: false },
			{ colvalue: 'Monthkey', coltext: 'Month', header: 'Month', sortbycol: 'Monthkey', groupbyrank: 2, pivot: true, result: false },

// Rows of the pivot table:            
			{ colvalue: 'Subject', coltext: 'Subject', header: 'Subject', sortbycol: 'Subject', groupbyrank: 1, pivot: false, result: false },
			{ colvalue: 'Student', coltext: 'Student', header: 'Student', sortbycol: 'Student', groupbyrank: 2, pivot: false, result: false },         

// Values of the pivot table:			
			{ colvalue: 'Score', coltext: 'Score', header: 'Score', sortbycol: 'Score', groupbyrank: null, pivot: false, result: true }
],
        
// data:		
rows: [........

**Comment by janusschmidt** [comment]
Thanks for your feedback.

I haven't ever had the use for this functionality and i don't think i'll get the time to do it.
But if you or someone else wants to make it, i'll be happy to review and merge it in.
