### ISSUE TITLE
Show result column name

### ISSUE THREAD

**Issue by simovesterinen** [janusschmidt/jquery.pivot#18]
Hi,

Is it possible to show result column names? In you example 8 there is two result column. Score & Score2. 
Would it possible to show the names of the columns under months?

![image](https://cloud.githubusercontent.com/assets/10296492/5695045/5a387264-9994-11e4-8307-933602926996.png)

Forgive my poor Paint skills :)

-Simo

**Comment by janusschmidt** [comment]
That is a good idea. Will look into it when i get the time. 
Or you could do it? :-)
