### ISSUE TITLE
Hide Null value rows from Level

### ISSUE THREAD

**Issue by simovesterinen** [janusschmidt/jquery.pivot#19]
Would it be possible to include parameter where said that if columnvalue is null then it is hidden for that level result?

See my example picture and json:

![image](https://cloud.githubusercontent.com/assets/10296492/5695062/72eb2d96-9995-11e4-8fe9-f47cf5612dd7.png)

{
        dataid: 'An optional sourcetable identifier',
        columns: [
			{ colvalue: 'Year_Name', coltext: 'Year_Name', header: 'Year_Name', sortbycol: 'Yearkey', groupbyrank: 1, pivot: true, result: false },
			{ colvalue: 'Month', coltext: 'Month', header: 'Month', sortbycol: 'Monthkey', groupbyrank: 2, pivot: true, result: false },
            { colvalue: 'Subject', coltext: 'Subject', header: 'Subject', sortbycol: 'Subject', groupbyrank: 3, pivot: false, result: false },
			{ colvalue: 'Student', coltext: 'Student', header: 'Student', sortbycol: 'Student', groupbyrank: null, pivot: true, result: false },         
			{ colvalue: 'Score', coltext: 'Score', header: 'Score', sortbycol: 'Score', groupbyrank: null, pivot: false, result: true }],
        rows: [
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'English', 'Student': 'Elisa', 'Score': '8.7', 'Score2': '18.27' },
			{ 'Yearkey':2015,'Year_Name':'2015','Monthkey':null, 'Month': null, 'Subject': null, 'Student': 'Elisa', 'Score': '888.7', 'Score2': '1888.27' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Maths', 'Student': 'Elisa', 'Score': '6.5', 'Score2': '16.25 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Science', 'Student': 'Elisa', 'Score': '5.8', 'Score2': '15.28 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Art', 'Student': 'Elisa', 'Score': '8.9', 'Score2': '18.29 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'History', 'Student': 'Elisa', 'Score': '8.1', 'Score2': '18.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'French', 'Student': 'Elisa', 'Score': '6.2', 'Score2': '16.22 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'February', 'Subject': 'English', 'Student': 'Elisa', 'Score': '5.1', 'Score2': '15.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Maths', 'Student': 'Elisa', 'Score': '7.2', 'Score2': '17.22 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Science', 'Student': 'Elisa', 'Score': '8.9', 'Score2': '18.29 ' },
			{ 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Art', 'Student': 'Elisa', 'Score': '8.3', 'Score2': '18.23 ' },
			{ 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'History', 'Student': 'Elisa', 'Score': '8.4', 'Score2': '18.24 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'French', 'Student': 'Elisa', 'Score': '5.7', 'Score2': '15.27 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'English', 'Student': 'Elisa', 'Score': '4.1', 'Score2': '14.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Maths', 'Student': 'Elisa', 'Score': '7.1', 'Score2': '17.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Science', 'Student': 'Elisa', 'Score': '4.1', 'Score2': '14.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Art', 'Student': 'Elisa', 'Score': '9.2', 'Score2': '19.22 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'History', 'Student': 'Elisa', 'Score': '9.1', 'Score2': '19.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'French', 'Student': 'Elisa', 'Score': '5.6', 'Score2': '15.26 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'english', 'Student': 'Mary', 'Score': '8.7', 'Score2': '18.27 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Maths', 'Student': 'Mary', 'Score': '5.3', 'Score2': '15.23 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Science', 'Student': 'Mary', 'Score': '3.5', 'Score2': '13.25 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'Art', 'Student': 'Mary', 'Score': '6.1', 'Score2': '16.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'History', 'Student': 'Mary', 'Score': '5.8', 'Score2': '15.28 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':100, 'Month': 'January', 'Subject': 'French', 'Student': 'Mary', 'Score': '9.2', 'Score2': '19.22 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'english', 'Student': 'Mary', 'Score': '6.8', 'Score2': '16.28 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Maths', 'Student': 'Mary', 'Score': '5.4', 'Score2': '15.24 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Science', 'Student': 'Mary', 'Score': '5.6', 'Score2': '15.26 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'Art', 'Student': 'Mary', 'Score': '5.9', 'Score2': '15.29 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'History', 'Student': 'Mary', 'Score': '6.1', 'Score2': '16.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':200, 'Month': 'February', 'Subject': 'French', 'Student': 'Mary', 'Score': '9.3', 'Score2': '19.23 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'english', 'Student': 'Mary', 'Score': '4.1', 'Score2': '14.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Maths', 'Student': 'Mary', 'Score': '3.5', 'Score2': '13.25 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Science', 'Student': 'Mary', 'Score': '4.1', 'Score2': '14.21 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'Art', 'Student': 'Mary', 'Score': '4.8', 'Score2': '14.28 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'History', 'Student': 'Mary', 'Score': '6.7', 'Score2': '16.27 ' },
            { 'Yearkey':2015,'Year_Name':'2015','Monthkey':300, 'Month': 'March', 'Subject': 'French', 'Student': 'Mary', 'Score': '9.0', 'Score2': '19.20 ' }]
    }

**Comment by janusschmidt** [comment]
I'm not quite sure what you mean. Hiding the rows you marked would give strange sums, that the user wouldn't understand (They don't add up).

Couldn't you just filter the data before making the pivot (eg. jquery.map)?
